name: Build RSDKv3
on:
  push:
    branches:
      - wii

jobs: 
  v3-wii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dkp-pacman
        run: |
          sudo apt update
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Syu --noconfirm
      - name: Install Toolchain
        run: |
          sudo dkp-pacman -S wii-dev --noconfirm
      - name: Install Dependencies
        run: |
          sudo dkp-pacman -S wii-sdl2 ppc-libogg ppc-libvorbis ppc-libvorbisidec ppc-libtheora --noconfirm
      - name: Build RSDKv3
        run: |
          cd RSDKv3.Wii
          source /etc/profile.d/devkit-env.sh
          make
          mv RSDKv3.Wii.dol boot.dol
          zip v3-wii.zip boot.dol hbc-data/meta.xml hbc-data/icon.png
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: v3-wii
          path: RSDKv3.Wii/v3-wii.zip