name: Build RSDKv3
on:
  push:
    branches:
      - wii

jobs: 
  v3-wii:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dkp-pacman
        run: |
          sudo apt update
          wget https://apt.devkitpro.org/install-devkitpro-pacman
          chmod +x ./install-devkitpro-pacman
          sudo ./install-devkitpro-pacman
          sudo dkp-pacman -Syu
      - name: Install Toolchain
        run: |
          sudo dkp-pacman -S wii-dev
      - name: Install Dependencies
        run: |
          sudo dkp-pacman -S wii-sdl2 ppc-libogg ppc-libvorbis ppc-libvorbisidec ppc-libtheora
      - name: Build RSDKv3
        run: |
          cd RSDKv3.Wii
          make
          mkdir bin
          cp RSDKv3.Wii.elf bin/
          cp RSDKv3.Wii.dol bin/
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: v3-wii
          path: bin
